sudo: false
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: "guhilling-github"
    token:
      secure: "PIVBggt+JPplyg9oy6BZwQH2zHSFEsPdTlaJcXXEbnumfGzRbcq4Dr1FXzWn1ZOas9cPv0tG5YHbMhTYvettSLssAWI12LzgcjdvlqFrn4PYwa4zux+xJYxfgHdrIay6sm4FfS59ERz5oC8BBab5rxBCSWsONYrw0lO1esYw4Wk="

language: java

install: /bin/true

matrix:
  include:
  - name: "Java 11"
    jdk: openjdk11
  - name: "Java 16"
    jdk: openjdk16

script:
  build/travis-build

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"

before_cache:
  build/cleanup-snapshots
